name: release

on:
  push:
    tags-ignore:
      - "v1"
      - "v1_*"
      - "v2"
      - "v2_*"
      - "v3"
      - "v3_*"
      - "v4"
      - "v4_*"

jobs:
  build:
    runs-on: ubuntu-latest
    container: setsoft/kicad_pybuild:latest
    outputs:
      DEB_NAME: ${{ steps.mdeb.outputs.DEB_NAME }}

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Build
        id: mdeb
        run: |
          make deb
          mv ../*.deb .
          echo "DEB_NAME="`ls *.deb` >> $GITHUB_OUTPUT
          mkdir output
          mv *.deb output

      - name: Store
        uses: actions/upload-artifact@v4
        with:
          name: package
          path: output

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Retrieve
        uses: actions/download-artifact@v4
        with:
          name: package

      - name: Debug
        run: |
          ls -la
          ls -la package

      - name: Release
        uses: docker://antonyurchenko/git-release:latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DRAFT_RELEASE: "false"
          PRE_RELEASE: "false"
          CHANGELOG_FILE: "CHANGELOG.md"
        with:
          args: |
            package/${{needs.build.outputs.DEB_NAME}}
